In [1]:
%matplotlib qt5

In [2]:
import numpy as np
import os

In [3]:
file = r'/dls/science/groups/e02/Mohsen/code/Git_Repos/My_Repository/create_sim_data_prismatic/xyz_files/Graphene_SW_mod1.xyz'

In [4]:
with open(file, 'r') as f:
    #data = np.genfromtxt(f, delimiter=' ', skip_header=1)
    data = np.genfromtxt(f, delimiter='  ', skip_header=2, skip_footer = 1,usecols = (1,2,3))

In [5]:
data

array([[ 0.3731,  4.5181,  1.1159],
       [ 0.3495,  8.6909,  1.1159],
       [ 0.3267, 12.8675,  1.1159],
       [ 0.3108, 17.0429,  1.1158],
       [ 2.781 ,  4.533 ,  1.116 ],
       [ 2.7568,  8.7038,  1.116 ],
       [ 2.733 , 12.8782,  1.1159],
       [ 2.7178, 17.0527,  1.1159],
       [ 5.1888,  4.5468,  1.116 ],
       [ 5.1647,  8.7156,  1.116 ],
       [ 5.1381, 12.8906,  1.116 ],
       [ 5.1238, 17.0668,  1.116 ],
       [ 7.5979,  4.5596,  1.116 ],
       [ 7.5739,  8.7255,  1.1161],
       [ 7.5404, 12.9035,  1.1161],
       [ 7.5286, 17.0835,  1.1161],
       [10.01  ,  4.5703,  1.116 ],
       [ 9.9855,  8.7321,  1.1162],
       [ 9.9373, 12.9175,  1.1162],
       [12.3238, 12.9362,  1.1162],
       [12.3344, 17.1218,  1.1162],
       [14.8513,  4.5563,  1.1161],
       [14.8236,  8.7431,  1.1162],
       [14.695 , 12.972 ,  1.1163],
       [14.7403, 17.13  ,  1.1161],
       [ 0.3655,  5.9081,  1.1159],
       [ 0.3411, 10.0811,  1.1159],
       [ 0.3209, 14.2579,  1

In [6]:
import matplotlib.pyplot as plt

In [9]:
fig, ax = plt.subplots()
#ax.scatter(data[:,0], data[:,1])
#ax.scatter(data_new[:,0], data_new[:,1])
ax.scatter(data[:,1], data[:,2])

In [14]:
data[:,0]

array([10.840352, 12.282852, 15.176452, ..., 79.362052, 80.081452,
       81.521152])

In [8]:
data_new = np.copy(data)
data_new[:,0] = data[:,0]+12
data_new[:,1] = data[:,1]+17
data_new

array([[23.6956, 19.4519,  3.777 ],
       [25.1532, 19.4583,  3.7316],
       [25.8828, 18.2321,  3.9299],
       [27.3315, 18.2438,  3.9492],
       [28.0689, 19.478 ,  3.7878],
       [29.5128, 19.4979,  3.8738],
       [19.4043, 21.7466,  3.9505],
       [20.6782, 21.741 ,  3.7583],
       [21.5966, 20.7333,  3.7456],
       [22.97  , 20.7078,  3.6013],
       [23.8553, 21.6959,  3.3503],
       [25.1728, 21.9182,  3.2601],
       [25.9052, 20.6739,  3.5024],
       [27.3518, 20.7011,  3.5425],
       [28.0896, 21.938 ,  3.3655],
       [29.5364, 21.9753,  3.5003],
       [30.2474, 20.7429,  3.7616],
       [31.687 , 20.7577,  3.9174],
       [32.4241, 22.0014,  3.8798],
       [26.0182, 22.9448,  3.0774],
       [27.3412, 23.1804,  3.0883],
       [28.1785, 24.225 ,  2.9889],
       [29.4882, 24.475 ,  3.1009],
       [30.2792, 23.2304,  3.4039],
       [31.7344, 23.244 ,  3.6388],
       [32.5238, 24.5033,  3.6513],
       [33.8886, 24.536 ,  3.9603],
       [30.3673, 25.513 ,  3

In [127]:
with open(file, 'r') as f:
    for i, line in enumerate(f):
        if i is 1:
            data = np.asarray(line.split(), dtype = float)

In [130]:
data

array([26.1719, 26.4031,  6.6485])

In [40]:
fig, ax = plt.subplots()

In [13]:
data.shape

(2430, 3)

In [37]:
max(data[:,0])

81.521152

In [36]:
data

array([[10.840352 ,  8.7739316,  5.306486 ],
       [12.282852 ,  8.7780116,  5.353765 ],
       [15.176452 ,  8.7914616,  5.42642  ],
       ...,
       [79.362052 , 82.4427416,  5.0129   ],
       [80.081452 , 83.6915416,  5.0039   ],
       [81.521152 , 83.6925416,  5.0625   ]])

In [99]:
data_new2

array([[11.6956,  2.4519,  3.777 ],
       [13.1532,  2.4583,  3.7316],
       [13.8828,  1.2321,  3.9299],
       [15.3315,  1.2438,  3.9492],
       [16.0689,  2.478 ,  3.7878],
       [17.5128,  2.4979,  3.8738],
       [ 7.4043,  4.7466,  3.9505],
       [ 8.6782,  4.741 ,  3.7583],
       [ 9.5966,  3.7333,  3.7456],
       [10.97  ,  3.7078,  3.6013],
       [11.8553,  4.6959,  3.3503],
       [13.1728,  4.9182,  3.2601],
       [13.9052,  3.6739,  3.5024],
       [15.3518,  3.7011,  3.5425],
       [16.0896,  4.938 ,  3.3655],
       [17.5364,  4.9753,  3.5003],
       [18.2474,  3.7429,  3.7616],
       [19.687 ,  3.7577,  3.9174],
       [20.4241,  5.0014,  3.8798],
       [14.0182,  5.9448,  3.0774],
       [15.3412,  6.1804,  3.0883],
       [16.1785,  7.225 ,  2.9889],
       [17.4882,  7.475 ,  3.1009],
       [18.2792,  6.2304,  3.4039],
       [19.7344,  6.244 ,  3.6388],
       [20.5238,  7.5033,  3.6513],
       [21.8886,  7.536 ,  3.9603],
       [18.3673,  8.513 ,  3

In [82]:
data_new = data[data[:,0] <90 ]
data_new = data_new[data_new[:,0] >55 ]
data_new = data_new[data_new[:,1] <53 ]
data_new = data_new[data_new[:,1] >25 ]

In [97]:
data_new2 = data_new[data_new[:,2] < 4 ]

In [83]:
data_new[:,0] = data_new[:,0] - min(data_new[:,0])
data_new[:,1] = data_new[:,1] - min(data_new[:,1])

In [103]:
max(data_new2[:,1])

8.513000000000002

In [98]:
fig, ax = plt.subplots()
#ax.scatter(data[:,0], data[:,1])
#ax.scatter(data_new[:,0], data_new[:,1])
ax.scatter(data_new2[:,0], data_new2[:,1])

In [10]:
check = data[:][:] <30.0

In [11]:
data_crop = data*check

In [24]:
data.shape

(2430, 4)

In [22]:
inds=[]
for (i,v) in enumerate(data_crop): 
    if ~np.all(data_crop[i]): 
        print(i,v)
        inds.append(i)
        #np.delete(data_crop,data_crop[i][:],0)

109 [2.6102 0.     1.1163]
113 [5.0152 0.     1.1163]
117 [7.4176 0.     1.1162]
121 [9.8181 0.     1.1162]
125 [12.2189  0.      1.1161]
129 [14.6261  0.      1.1161]
133 [0.2265 0.     1.1162]
137 [2.6341 0.     1.1162]
141 [5.0399 0.     1.1162]
145 [7.4446 0.     1.1162]
149 [9.8482 0.     1.1161]
153 [12.2498  0.      1.116 ]
157 [14.6481  0.      1.1159]
161 [1.4246 0.     1.1162]
165 [3.8314 0.     1.1162]
169 [6.2361 0.     1.1162]
173 [8.6395 0.     1.1162]
177 [11.0412  0.      1.1161]
181 [13.4409  0.      1.116 ]
185 [1.4124 0.     1.1163]
189 [3.8188 0.     1.1163]
193 [6.2227 0.     1.1162]
197 [8.6252 0.     1.1162]
201 [11.0271  0.      1.1161]
205 [13.4313  0.      1.1161]
304 [17.0523  0.      1.1161]
308 [19.5007  0.      1.1161]
312 [21.9422  0.      1.1162]
316 [24.3544  0.      1.1165]
320 [26.7503  0.      1.1167]
327 [17.0436  0.      1.1159]
331 [19.4533  0.      1.1159]
335 [21.8788  0.      1.116 ]
339 [24.2728  0.      1.1162]
343 [26.6714  0.      1.1165]
3

In [23]:
data_crop[391][:]

array([25.5301,  0.    ,  1.1165])

In [29]:
data_crop = np.delete(data_crop,inds, 0)

In [30]:
data_crop.shape

(348, 3)

In [28]:
ax.scatter(test[:,0], test[:,1], c='g')

In [51]:
col = np.ones(shape = (data.shape[0],1))
data_new = np.concatenate((6*col,data,col,0.08*col), axis=1)

In [52]:
#data_new = np.round(data_new, decimals=1)
data_new

array([[ 6.    ,  0.3731,  4.5181,  1.1159,  1.    ,  0.08  ],
       [ 6.    ,  0.3495,  8.6909,  1.1159,  1.    ,  0.08  ],
       [ 6.    ,  0.3267, 12.8675,  1.1159,  1.    ,  0.08  ],
       ...,
       [ 6.    , 27.888 , 24.6038,  1.116 ,  1.    ,  0.08  ],
       [ 6.    , 27.8285, 28.7596,  1.1164,  1.    ,  0.08  ],
       [ 6.    , 27.9322, 32.9159,  1.1168,  1.    ,  0.08  ]])

In [23]:
np.savetxt('Z:\Mohsen\code\sim_4DSTEM\graphene_SW\Graphene_SW_new.txt',data_new, header ='29.03 32.442 0.000' , footer = '-l',encoding='UTF-8')

In [9]:
file = '/dls/science/groups/e02/Mohsen/code/sim_4DSTEM/ptypy_pycho_sim_matrix/create_sim_data_prismatic/xyz_files/graphene_island_doped_extended.txt'
with open(file, 'a') as f:
    for row in data_new:
        f.write('6  '+ str(row[0])+ '  '+ str(row[1])+ '  '+ str(row[2])+ '  1'+ '  0.0800 \n')


In [36]:
np.max(data_crop)

29.7623

In [36]:
import matplotlib.pyplot as plt

In [37]:
fig, ax = plt.subplots(1,1)

In [38]:
ax.scatter(data[:,0], data[:,1], data[:,2])

In [39]:
plt.show()

In [16]:
# defect-free case
file = r'Z:\Mohsen\code\sim_4DSTEM\bilayer_no_defects\Mohsen_graphene_2_layers_4_7_tile.txt'

In [18]:
with open(file, 'r') as f:
    nodef_data = np.genfromtxt(f, skip_header=2,skip_footer=1, usecols=(1,2,3))

In [19]:
nodef_data

array([[ 0.      ,  1.21    ,  0.      ],
       [ 2.095781,  0.      ,  0.      ],
       [ 0.      ,  3.63    ,  0.      ],
       [ 2.095781,  2.42    ,  0.      ],
       [ 4.191563,  1.21    ,  0.      ],
       [ 6.287344,  0.      ,  0.      ],
       [ 0.      ,  6.05    ,  0.      ],
       [ 2.095781,  4.84    ,  0.      ],
       [ 4.191563,  3.63    ,  0.      ],
       [ 6.287344,  2.42    ,  0.      ],
       [ 8.383126,  1.21    ,  0.      ],
       [10.478907,  0.      ,  0.      ],
       [ 0.      ,  8.47    ,  0.      ],
       [ 2.095781,  7.26    ,  0.      ],
       [ 4.191563,  6.05    ,  0.      ],
       [ 6.287344,  4.84    ,  0.      ],
       [ 8.383126,  3.63    ,  0.      ],
       [10.478907,  2.42    ,  0.      ],
       [12.574689,  1.21    ,  0.      ],
       [14.67047 ,  0.      ,  0.      ],
       [ 0.      , 10.89    ,  0.      ],
       [ 2.095781,  9.68    ,  0.      ],
       [ 4.191563,  8.47    ,  0.      ],
       [ 6.287344,  7.26    ,  0. 

In [25]:
max(nodef_data[:,0])

16.067658

In [22]:
max(nodef_data[:,1])

15.73

In [26]:
max(nodef_data[:,2])

3.395

In [54]:
nodef_data.dtype

dtype('float64')